window.ENV_VARS = {
    "NEXT_PUBLIC_TORII_URL": "%NEXT_PUBLIC_TORII_URL%",
    "NEXT_PUBLIC_KATANA_URL": "%NEXT_PUBLIC_KATANA_URL%",
    "NEXT_PUBLIC_WORLD_ADDRESS": "%NEXT_PUBLIC_WORLD_ADDRESS%",
    "NEXT_PUBLIC_EVOLUTE_DUEL_GAME": "%NEXT_PUBLIC_EVOLUTE_DUEL_GAME%",
    "NEXT_PUBLIC_EVOLUTE_DUEL_PROFILE_ACTIONS": "%NEXT_PUBLIC_EVOLUTE_DUEL_PROFILE_ACTIONS%"
};
